import mongoose from 'mongoose';

const { Schema } = mongoose;

const ClaimsSchema = new Schema({
  companyReference: { type: String, required: true },
  policyNumber: { type: String, required: true },
  partnerRef: { type: String, required: true },
  incidentDetails: {
    incidentDate: { type: Date, required: true },
    accidentCircumstances: { type: String },
    damageToVehicle: { type: String },
    preExistingDamage: { type: String },
  },
  vehicleDetails: {
    registrationNumber: { type: String, required: true },
    make: { type: String },
    model: { type: String },
    engineSize: { type: String },
    registrationDate: { type: Date },
    vehicleStatus: { type: String },
    imsVehicleStatus: { type: String },
  },
  thirdPartyDetails: {
    insurer: { type: String },
    ref: { type: String },
    client: { type: String },
    registration: { type: String },
  },
  driverDetails: {
    firstName: { type: String, required: true },
    lastName: { type: String, required: true },
    title: { type: String },
    address: {
      addressLine1: { type: String },
      postcode: { type: String },
    },
    contact: {
      homeTelephone: { type: String },
      workTelephone: { type: String },
      mobileTelephone: { type: String },
      fax: { type: String },
      email: { type: String },
    },
  },
  repairerDetails: {
    repairerName: { type: String },
    contact: {
      telephone: { type: String },
      mobileTelephone: { type: String },
      email: { type: String },
      fax: { type: String },
    },
    repairTimeline: {
      bookingInDate: { type: Date },
      mobileEstimateDate: { type: Date },
      dateIn: { type: Date },
      estimateReceivedDate: { type: Date },
      authorisedDate: { type: Date },
      authorisedAmounts: {
        parts: { type: Number },
        labour: { type: Number },
        paintAndMaterials: { type: Number },
        specialist: { type: Number },
      },
      supplementaryAuthorisedDate: { type: Date },
      supplementaryAuthorisedAmounts: { type: Number },
      supplementaryReason: { type: String },
      calculatedRepairDays: { type: Number },
      estimatedCompletionDate: { type: Date },
      revisedEstimatedCompletionDate: { type: Date },
      repairCompletionDate: { type: Date },
      dateOut: { type: Date },
      invoiceReceivedDate: { type: Date },
      invoiceApprovedDate: { type: Date },
      invoiceRejectedReasons: { type: String },
    },
  },
  salvageDetails: {
    salvageAmount: { type: Number },
    salvageCategory: { type: String },
    salvageAgentName: { type: String },
    contact: {
      workTelephone: { type: String },
      mobileTelephone: { type: String },
      fax: { type: String },
      email: { type: String },
    },
    salvageInstructedDate: { type: Date },
    salvageCollectedDate: { type: Date },
    salvageClearedDate: { type: Date },
    salvageLotNumber: { type: String },
    salvageValuePaid: { type: Number },
    salvageValueReceived: { type: Number },
  },
  financialDetails: {
    repairCost: {
      net: { type: Number },
      vat: { type: Number },
      gross: { type: Number },
    },
    totalLossFee: {
      net: { type: Number },
      vat: { type: Number },
      gross: { type: Number },
    },
    storageAndRecovery: {
      net: { type: Number },
      vat: { type: Number },
      gross: { type: Number },
      ref: { type: String },
    },
    engineersFee: {
      net: { type: Number },
      vat: { type: Number },
      gross: { type: Number },
    },
    deliveryAndCollection: {
      net: { type: Number },
      vat: { type: Number },
      gross: { type: Number },
    },
    excess: { type: Number },
    totalExcess: { type: Number },
    pav: { type: Number },
    tpiPavPayment: { type: Number },
    salvageValuePaid: { type: Number },
    salvageValueReceived: { type: Number },
  },
  statusDetails: {
    status: { type: String, required: true },
    clsp: { type: String },
    billingStatus: { type: String },
    cdStatus: { type: String },
    fault: { type: String },
    underpinned: { type: Boolean },
    replacementVehicle: { type: Boolean },
    schemeName: { type: String },
    schemeCompanyReference: { type: String },
    subrogated: { type: Boolean },
  },
  timestamps: {
    notificationDate: { type: Date },
    tlDate: { type: Date },
    tLCallDate: { type: Date },
    tLChaseDates: [{ type: Date }],
    v5CReceivedDate: { type: Date },
    motReceivedDate: { type: Date },
    financeLetterReceivedDate: { type: Date },
    packSubmittedToTPIDate: { type: Date },
    imagesReceivedDate: { type: Date },
    customerRetaining: { type: Boolean },
  },
  notes: {
    repairDelayNotes: { type: String },
    valuationDisputeNotes: { type: String },
    tpiPavPaymentChaseNotes: { type: String },
  },
});

const Claims = mongoose.model('Claims', ClaimsSchema);
export default Claims;